### ISSUE TITLE
Paste as HTML doesn't work

### ISSUE THREAD

**Issue by mquan86** [cetinkaya/pastefromhtml#14]
I have Zim 0.74.3 installed as portable (Windows 10) with plugin pastefromhtml enabled (workaround in #12).

I'm not sure if I understand the usage of this plugin correct. Assume that mean I can copy some certain web content and paste it to Zim will keep similar format. So I copy a list items from any random web page and then "Paste as HTML" to Zim, but nothing happens (no any content was pasted). Check log file of Zim and see no error log.

Log snippet:
```
DEBUG: BackgroundCheck finished
DEBUG: Action: pastefh
DEBUG: Action: show_debug_log
```

Video: https://user-images.githubusercontent.com/13567269/191620584-3f9f0d60-2682-45d9-8448-356f26c21fb0.mp4

**Comment by cetinkaya** [comment]
Thank you for opening a separate issue. I guess you are using Microsoft Edge as your browser. I made some changes in bd41af594ab411bc250aecac63b974716775a27e to support pasting from Microsoft Edge. 

If you update the pastefromhtml plugin to the newest version and use the workaround in #12 again, you should be able to paste from Microsoft Edge. 

If you are not using Microsoft Edge or the updated plugin still doesn't work, could you let me know?

**Comment by mquan86** [comment]
I have to say you did an excellent job.

I didn't know your plugin doesn't support Chrome/Edge. So after upgrade the latest version it works now on both Chrome and Edge.

Close the case.
Thank you so much.
