### ISSUE TITLE
I see markdown source instead of rendered content after paste

### ISSUE THREAD

**Issue by tuttle** [cetinkaya/pastefromhtml#16]
Hi, this plugin helps me a lot! Thanks for it.

But I need to restart zim to get the pasted content rendered. At first it is displayed as markdown source. 

I use zim version 0.74.3. Could this be due to an old version?

**Comment by cetinkaya** [comment]
I am sorry for my late response. I will try to see if it is possible to reload the page automatically after pasting. For now, we can use CTRL+R or click Menu/View/Reload.

**Comment by tuttle** [comment]
Ok, thanks. What else worked for me is Cut and then Paste the new content. So I stopped doing full restarts. :-D

**Comment by cetinkaya** [comment]
I have added an option to reload the page automatically after pasting. This will render the pasted content right after pasting. It is turned off by default. To turn it on, you can click on the menu item Edit/Preferences then choose Plugins tab, find and click on "Paste from HTML" in the list on the left and then click on the Configure button on the right. 
![screenshot_2024-01-20-22-42-44](https://github.com/cetinkaya/pastefromhtml/assets/3178761/22588288-f7ea-40ce-bc91-1f32b536f72f)
