### ISSUE TITLE
suggestion: move menu entry to "Edit" sub menu and add to context menu

### ISSUE THREAD

**Issue by Simplenuity** [cetinkaya/pastefromhtml#17]
Thanks @cetinkaya for this great tool! It has hugely improved my workflow.

After a very long time of using it am nevertheless intuitively expecting the menu item in two places:
* under the "Edit" sub menu
* in the right-click context menu

Would it be possible to place it there or is this per se not possible due to the structure of the code?

Thanks for your consideration!

**Comment by cetinkaya** [comment]
It may be possible. I will work on this.

**Comment by cetinkaya** [comment]
I have added an entry in the "Edit" menu. 

However, adding an entry in the "right-click" context menu appears to be difficult. One option is to extend the PageView class with a special do_populate_popup method and then replace the original pageview with the custom one. But this may break things. I will keep this issue open and further think about it.
